### ISSUE TITLE
NoMethodError: undefined method `collation' for nil:NilClass

### ISSUE THREAD

**Issue by jmuheim** [barsoom/traco#33]
I have added traco gem to mu project.

When trying to save an object now, I get the following:

```
NoMethodError at /en/pages
undefined method `collation' for nil:NilClass
```

Here's what I've done so far: https://github.com/jmuheim/base/pull/84

Any idea what's the problem?

**Comment by henrik** [comment]
Hi! Could you provide the full backtrace showing that error? The Traco doesn't call a "collate" method directly, so I'd need it to see where it happens exactly.

**Comment by henrik** [comment]
Closing this since I did not hear back – @jmuheim, feel free to add that backtrace if you have the opportunity, and I'll reopen.
