### ISSUE TITLE
Is this gem compatible with Rails 5.x?

### ISSUE THREAD

**Issue by brendon** [barsoom/traco#36]
I haven't noticed any issues so far, but would you be open to using `Appraisals` to test this gem against currently supported Rails versions?

**Comment by henrik** [comment]
Hi! Our main project is still on Rails 4; I don't know off the top of my head if we're using it on a Rails 5 project.

That sounds like a great idea. I'd be glad to accept a PR to get that running on Travis :)

**Comment by henrik** [comment]
I'll close this issue, but again, happy to accept a PR!

**Comment by brendon** [comment]
Roger :) I'll get that set up. I'm just upgrading a project from 4.2 to 5.2 so just trying to line up all the ducks :)
